### ISSUE TITLE
IPAG: PRE entry - Wiederholter Bezug pro Arzneimittel

### ISSUE THREAD

**Issue by ziegm** [hl7ch/hl7ch-cda#34]
![image](https://user-images.githubusercontent.com/32767151/198265811-be7cdbd7-f050-472c-9447-4ca30132da14.png)

**Comment by ziegm** [comment]
Abbildung FHIR ([Profil](http://build.fhir.org/ig/hl7ch/ch-emed/StructureDefinition-ch-emed-medicationrequest.html)):
MedicationRequest.dispenseRequest.numberOfRepeatsAllowed 0..1: Repeated supply per medication (without initial dispense)

Die Angabe ist optional, das heisst, falls in der Praxis nicht angegeben wird, muss es im Austauschformat auch nicht angegeben werden.

Wiederholter Bezug pro Arzneimittel ist ein Element des Minimal Data Sets. [Hier](http://build.fhir.org/ig/hl7ch/ch-emed/repeated-dispense.html) werden die Anwendungsfälle detailliert beschrieben im FHIR IG.

Entscheid Issue zu schliessen (PJ/OE/MZ)

**Comment by pjolo** [comment]
Rückmeldung IPAG:
Hier noch eine zusätzliche Anmerkung: Die forcierte Abgabe kann erfasst werden, es verletzt jedoch die strukturierte Integrität des PML. Bei einer forcierten Abgabe gibt es kein korrespondierendes Rezeptdokument. Es muss diskutiert werden, ob diese strukturelle Integrität notwendig ist, z. B. für Abfragen in der Zukunft.

**Comment by ziegm** [comment]
17.11.2022 Telco PJ/OE/MZ
@pjolo klärt es weiter ab.

**Comment by pjolo** [comment]
Rückmeldung IPAG:
**Forcierte Abgabe:** Die Apothekerin darf unter Angabe eines Grundes ein Rezept nochmals wiederholen, auch wenn es nicht mehr gültig wäre. Verrechnung erfolgt direkt an die Krankenkasse. Normalerweise nur für nicht repetierbare Rezepte.

**Strukturverletzung:** Siehe z. B. Use Case [#1 IHE](https://www.ihe.net/uploadedFiles/Documents/Pharmacy/IHE_Pharmacy_Suppl_PML.pdf#page=12) Request Medication List; «The physician requests the Medication List and receives the document containing all dispenses and medication administrations for a period of time and all prescriptions which are still ready to be dispensed. He also gets all planned medications in order to have an exhaustive view of the medication treatment plan of the patient.» 
Die Struktur-Integrität bezieht sich auf die Vollständigkeit aller relevanten Dokumente zur eMedikation.

Der letzte Punkt müsste im Rahmen der Umsetzung Phase 3 eMedikation entschieden werden.

PJ: Meiner Meinung nach ist dieser Punkt mehr ein prozessuales Problem als ein technisches Problem. Wir werden dies aber bei der Phase 3 berücksichtigen. Aktuell muss an der Spezifikation und an diesem Ticket nichts mehr unternommen werden.
